project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
preserve_hierarchy: true

files:
  - source: "Wiki posts/**/*.md"
    translation: "i18n/%two_letters_code%/%original_path%/%original_file_name%"
    update_option: "update_as_unapproved"
